# Generated by Django 6.1.1 on 2026-09-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketassist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aianalysis',
            old_name='suggested_catrgory',
            new_name='suggested_category',
        ),
    ]
